# Enforces encryption at rest for all storage services
apiVersion: security.cloud/v1
kind: StorageEncryptionPolicy
metadata:
  name: enforce-storage-encryption
spec:
  defaultEncryption:
    enabled: true
    algorithm: AES-256
    keyManagement:
      provider: KMS
      keyRotation: true
      rotationPeriodDays: 90

  storageTypes:
    blockStorage:
      encrypted: true
      allowUnencryptedVolumes: false

    objectStorage:
      encrypted: true
      defaultEncryption: SSE-KMS
      publicAccessBlocked: true
      versioningEnabled: true

    databaseStorage:
      encrypted: true
      allowUnencryptedInstances: false
      backupEncryption: true

  compliance:
    standards:
      - ISO27001
      - SOC2
      - PCI-DSS

  enforcement:
    onViolation:
      action: deny
      message: "Unencrypted storage resources are not allowed"
